# Generated by Django 6.1.1 on 2026-09-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='casa',
            new_name='numero',
        ),
    ]
